apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              value: "mongodb://mongodb-0.mongodb-headless.default.svc.cluster.local:27017,mongodb-1.mongodb-headless.default.svc.cluster.local:27017/?replicaSet=rs0"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: server